spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

logging:
  level:
    org:
      hibernate:
        type: trace

h2:
  console.enabled: true

  jpa:
    show_sql: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        ddl-auto: create-drop
