spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password: sa

  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
        SQL: debug

h2:
  console.enabled: true

  jpa:
    show_sql: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        ddl-auto: create-drop

security:
  jwt:
    expiration: 300
    signatureKey: thisIsATest
